### ISSUE TITLE
diff does not display for first item.

### ISSUE THREAD

**Issue by leeahoward** [CJTozer/SublimeDiffView#48]
When I start diffview the diff for the first item does not show.  If there are two then I can move to the next and move back to display it, but if there is only one there is no way to get it to show up. 
![image](https://user-images.githubusercontent.com/900770/27691773-1014f420-5cb3-11e7-9ae4-46a6658580f2.png)

**Comment by CJTozer** [comment]
Interesting - can I check a few things:

* what VCS are you using?
* what parameters (if any) did you pass to the command
* is there any output on the console (visible by pressing ``` ⌃ + ` ``` on Mac apparently (see [here](http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_osx.html#general)))

If that doesn't give anything interesting, perhaps you could retry with `debug: true` in the DiffView package settings, and let me have the ST console output from that.

**Comment by leeahoward** [comment]
VCS: git
parameters: none
console output:
```
SublimeLinter: find_posix_python: python3 => None 
SublimeLinter: find_posix_python: python3 => None 
SublimeLinter: find_posix_python: python => /usr/local/bin/python 
SublimeLinter: find_python: system python = /usr/local/bin/python 
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7} 
SublimeLinter: find_python: <= (None, None, 2, 7) 
SublimeLinter: no python 3 available to augment sys.path 
SublimeLinter: pyyaml imported <module 'yaml' from '/Users/leehoward/Library/Application Support/Sublime Text 3/Packages/pyyaml/st3/yaml/__init__.py'> 
Package Control: No updated packages
/Users/leehoward/Library/Application Support/Sublime Text 3
LOADING BOOKMARKS
Traceback (most recent call last):
  File "DiffView in /Users/leehoward/Library/Application Support/Sublime Text 3/Installed Packages/DiffView.sublime-package", line 89, in do_diff
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
SublimeLinter: pyyaml activated: <builtin> 
SublimeLinter: pyyaml: docker-compose.yml <builtin> 
Traceback (most recent call last):
  File "DiffView in /Users/leehoward/Library/Application Support/Sublime Text 3/Installed Packages/DiffView.sublime-package", line 89, in do_diff
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
SublimeLinter: pyyaml: docker-compose.yml <builtin> 
SublimeLinter: pyyaml: docker-compose.yml <builtin> 
SublimeLinter: pyyaml: docker-compose.yml <builtin> 
no command for selector: noop:
```

Thanks!

**Comment by CJTozer** [comment]
Thanks.  So, that's actually complaining because it can't find the filename of the current view - do you have any files open when you run the command?

I'd expect to see something different I think to get the screenshot you gave me.  (Does the test you just ran show the same symptoms?))

Clearly we can do better with an error message popup if there's no current file (that's how the plugin works out which repository to get changes from).

**Comment by leeahoward** [comment]
Looks like you are correct.  When the file is open there is no output in the console.  

I also noticed that it works fine the first time I run it after starting sublime.  The second time it fails to show the contents.  

Here is the output in debug mode.  

```
DiffView running in debug mode
DiffView running in debug mode
**** Running VCS command:
git diff --stat=9999 
** VCS command returns output:
b' content/assets/components/signIn/signIn.controller.js | 1 +\n 1 file changed, 1 insertion(+)\n'
**** Running VCS command:
git diff  -U0 -- "content/assets/components/signIn/signIn.controller.js"
** VCS command returns output:
b'diff --git a/content/assets/components/signIn/signIn.controller.js b/content/assets/components/signIn/signIn.controller.js\nindex 3203cb4..a1514de 100644\n--- a/content/assets/components/signIn/signIn.controller.js\n+++ b/content/assets/components/signIn/signIn.controller.js\n@@ -48,0 +49 @@ export default function SignInController ($rootScope, $scope, $location, $cookie\n+            \n'
**** Running VCS command:
git show HEAD:"content/assets/components/signIn/signIn.controller.js"
** VCS command returns output:
b'\'use strict\';\n\nexport default function SignInController ($rootScope, $scope, $location, $cookies, $q, $http, LoginHelperService, SSO_ACTIVE) {\n  \'ngInject\';\n    $scope.user = [];\n    $scope.loading = false;\n\n    if ( $rootScope.isLoggedIn ) {\n        $location.path("/dashboard");\n    }\n\n    $scope.submit = function () {\n        $scope.error = "";\n        var isValid = $rootScope.isValid($scope.parent);\n        if( !isValid.success ){\n            // console.log(\'not valid: \'+isValid.name);\n            $(\'[name="\'+isValid.name+\'"]\').focus();\n            return;\n        }\n\n        // send username to rootScope to use with recoverAccount controller\n        $rootScope.user.username = $scope.user.username;\n\n        $scope.loading = true;\n\n        LoginHelperService.initiate($scope.user)\n        .then(function (result) {\n\t            $("#ahec-menu-bar").find("[data-user-name]").text($cookies.get(\'name\').replace(/\\+/g,\' \'));\n\n\t            if ( SSO_ACTIVE ) {\n\t                LoginHelperService.sso()\n\t                .then(\n                        // sso success\n                        function () {\n    \t                \tLoginHelperService.handleLoginSuccess();\n    \t\t            },\n                        // sso failure\n                        // login was ok, so continue..\n                        function () {\n                            LoginHelperService.handleLoginSuccess();\n                        }\n                    );\n\t            }\n\t            else {\n\t            \tLoginHelperService.handleLoginSuccess();\n\t            }\n\n\t        },\n\n\t        // login response rejections\n\t        function loginError(result) {\n                // switch to allow custom messages to be displayed to user\n                switch(result.status){\n                    case 232:\n                        // Account found found  - verification is not complete\n                    case 233:\n                        // Login Failed. Password Mismatch. User may retry or recover password\n                    case 234:\n                        // Login failed. User not found\n                    case 235:\n                        // CASCE record found. User must create an account to sign in.\n                    case 422:\n                        // oauth failure\n                        $scope.error = result.data;\n                        $scope.loading = false;\n                        break;\n                    default:\n                        // handle unexpected status codes here\n                        $scope.error = {messages:[\'Unexpected error processing login, please try again.\']};\n                        $scope.loading = false;\n                }\n\t        }\n\t    );\n    };\n};\n'
```
and a screenshot 
![image](https://user-images.githubusercontent.com/900770/27735376-302ad706-5d6d-11e7-95d6-6f6c86139958.png)

**Comment by leeahoward** [comment]
Looks like current_row is not getting reset when DiffView is loaded/unloaded.  That's why it works the first time and not the second.  
I modified to update current_row in start_listen and it works.  


```
    def start_listen(self, cb, view, diff):
        """Start listening for the changes list.

        Args:
            cb: The callback to call when a widget is created.
            view: The view to listen for.
            diff: The diff currently being run.
        """
        self.cb = cb
        self.view = view
        self.diff = diff
        self._listening = True

        # add this
        self.current_row = -1
```

**Comment by CJTozer** [comment]
Thanks @leeahoward I've done some extra testing and that fix looks good.  Update will be live shortly.

Thanks again for raising/providing the fix!
